import { useEffect, useState } from "react";
import { Api } from "../Servicios/ClienteApi.js";
import { Boton, Campo, Mensaje, Seccion } from "../Componentes/Comunes.jsx";

export default function PaginaAdministrador() {
  const [Datos, DefinirDatos] = useState({ SolicitudesCaja: [], Cajeros: [], Alertas: [] });
  const [Mensaje, DefinirMensaje] = useState("");
  const [MontoInicial, DefinirMontoInicial] = useState("1000");
  const [Nuevo, DefinirNuevo] = useState({ nombre: "", correo: "", clave: "" });
  const [Inspector, DefinirInspector] = useState({ correo: "", clave: "" });
  async function Cargar() { try { DefinirDatos(await Api.Get("/administrador/resumen")); } catch (Error) { DefinirMensaje(Error.message); } }
  useEffect(() => { Cargar(); }, []);
  async function Resolver(Id, Aprobar, Tipo) { try { await Api.Post(`/administrador/solicitudes-caja/${Id}`, { aprobar: Aprobar, monto: Tipo === "APERTURA" ? Number(MontoInicial) : null }); DefinirMensaje(Aprobar ? "Solicitud aprobada." : "Solicitud rechazada."); await Cargar(); } catch (Error) { DefinirMensaje(Error.message); } }
  async function CrearCajero(Evento) { Evento.preventDefault(); try { await Api.Post("/administrador/cajeros", Nuevo); DefinirNuevo({ nombre: "", correo: "", clave: "" }); DefinirMensaje("Cajero creado."); await Cargar(); } catch (Error) { DefinirMensaje(Error.message); } }
  async function Quitar(Id) { try { await Api.Delete(`/administrador/cajeros/${Id}`); DefinirMensaje("Cajero desactivado."); await Cargar(); } catch (Error) { DefinirMensaje(Error.message); } }
  async function GuardarInspector(Evento) { Evento.preventDefault(); try { await Api.Put("/administrador/inspector", Inspector); DefinirMensaje("Credenciales del inspector actualizadas."); DefinirInspector({ correo: "", clave: "" }); await Cargar(); } catch (Error) { DefinirMensaje(Error.message); } }
  return <div className="pagina"><h1>Administración operativa</h1><p>Autoriza las cajas, administra cajeros y modifica las credenciales del único inspector.</p><Mensaje>{Mensaje}</Mensaje><Seccion titulo="Solicitudes de caja"><Campo etiqueta="Fondo inicial para aperturas" type="number" step="0.01" value={MontoInicial} onChange={(e) => DefinirMontoInicial(e.target.value)} />{Datos.SolicitudesCaja?.length ? <div className="tabla-contenedor"><table><thead><tr><th>Cajero</th><th>Tipo</th><th>Monto</th><th>Detalle</th><th>Decisión</th></tr></thead><tbody>{Datos.SolicitudesCaja.map((Item) => <tr key={Item.id}><td>{Item.cajero_nombre}</td><td>{Item.tipo}</td><td>{Item.monto || Item.monto_contado || "-"}</td><td>{Item.detalle}</td><td><div className="acciones-tabla"><Boton onClick={() => Resolver(Item.id, true, Item.tipo)}>Aprobar</Boton><Boton peligro onClick={() => Resolver(Item.id, false, Item.tipo)}>Rechazar</Boton></div></td></tr>)}</tbody></table></div> : <Mensaje>No existen solicitudes pendientes.</Mensaje>}</Seccion><Seccion titulo="Cajeros"><form className="rejilla tres" onSubmit={CrearCajero}><Campo etiqueta="Nombre" value={Nuevo.nombre} onChange={(e) => DefinirNuevo({ ...Nuevo, nombre: e.target.value })} required /><Campo etiqueta="Correo" type="email" value={Nuevo.correo} onChange={(e) => DefinirNuevo({ ...Nuevo, correo: e.target.value })} required /><Campo etiqueta="Contraseña inicial" type="password" minLength="8" value={Nuevo.clave} onChange={(e) => DefinirNuevo({ ...Nuevo, clave: e.target.value })} required /><Boton>Crear cajero</Boton></form><div className="tabla-contenedor"><table><thead><tr><th>Nombre</th><th>Correo</th><th>Estado</th><th>Acción</th></tr></thead><tbody>{Datos.Cajeros?.map((Item) => <tr key={Item.id}><td>{Item.nombre}</td><td>{Item.correo}</td><td>{Item.activo ? "Activo" : "Inactivo"}</td><td>{Item.activo && <Boton peligro onClick={() => Quitar(Item.id)}>Quitar</Boton>}</td></tr>)}</tbody></table></div></Seccion><Seccion titulo="Único inspector"><p>Actual: <b>{Datos.Inspector?.nombre}</b> — {Datos.Inspector?.correo}</p><form className="rejilla dos" onSubmit={GuardarInspector}><Campo etiqueta="Nuevo correo" type="email" value={Inspector.correo} onChange={(e) => DefinirInspector({ ...Inspector, correo: e.target.value })} /><Campo etiqueta="Restablecer contraseña" type="password" minLength="8" value={Inspector.clave} onChange={(e) => DefinirInspector({ ...Inspector, clave: e.target.value })} /><Boton>Guardar cambios</Boton></form></Seccion><Seccion titulo="Alertas de descuadre">{Datos.Alertas?.length ? Datos.Alertas.map((Item) => <div className={`alerta-admin ${Item.leida ? "leida" : ""}`} key={Item.id}><div><b>{Item.tipo}</b><p>{Item.mensaje}</p></div>{!Item.leida && <Boton secundario onClick={async () => { await Api.Put(`/administrador/alertas/${Item.id}`, {}); await Cargar(); }}>Marcar leída</Boton>}</div>) : <Mensaje>No hay alertas.</Mensaje>}</Seccion></div>;
}
