import { useEffect, useState } from "react";
import { Api, AbrirArchivoProtegido } from "../Servicios/ClienteApi.js";
import { Area, Boton, Mensaje as Aviso, Seccion } from "../Componentes/Comunes.jsx";

export default function PaginaInspector() {
  const [Datos, DefinirDatos] = useState({ Inspecciones: [] });
  const [Detalle, DefinirDetalle] = useState(null);
  const [Observaciones, DefinirObservaciones] = useState("");
  const [Mensaje, DefinirMensaje] = useState("");
  async function Cargar() { try { DefinirDatos(await Api.Get("/inspector/hoy")); DefinirDetalle(null); } catch (Error) { DefinirMensaje(Error.message); } }
  useEffect(() => { Cargar(); const F = () => Cargar(); window.addEventListener("tiempoActualizado", F); return () => window.removeEventListener("tiempoActualizado", F); }, []);
  async function Abrir(Id) { try { const R = await Api.Get(`/inspector/inspecciones/${Id}`); DefinirDetalle(R.Inspeccion); DefinirObservaciones(""); } catch (Error) { DefinirMensaje(Error.message); } }
  async function Aprobar() { try { const R = await Api.Post(`/inspector/inspecciones/${Detalle.id}/aprobar`, {}); DefinirMensaje(`Licencia aprobada. Vence el ${R.FechaVencimientoFormateada}.`); await Cargar(); } catch (Error) { DefinirMensaje(Error.message); } }
  async function Observar() { try { const R = await Api.Post(`/inspector/inspecciones/${Detalle.id}/observar`, { observaciones: Observaciones }); DefinirMensaje(R.Estado === "RECHAZADO" ? "El trámite fue rechazado después de la segunda inspección." : `Segunda inspección programada para ${R.FechaSegundaFormateada}.`); await Cargar(); } catch (Error) { DefinirMensaje(Error.message); } }
  return <div className="pagina"><h1>Inspecciones del día</h1><p>Fecha simulada: <b>{Datos.Fecha || "-"}</b>. Solo se muestran las inspecciones pendientes de hoy, con un máximo de cuatro.</p><Aviso>{Mensaje}</Aviso>{!Detalle && <Seccion titulo={`Pendientes (${Datos.Inspecciones?.length || 0}/4)`}>{Datos.Inspecciones?.length ? <div className="tarjetas">{Datos.Inspecciones.map((Item) => <button className="tarjeta seleccionable" key={Item.id} onClick={() => Abrir(Item.id)}><strong>{Item.razon_social}</strong><span>RUC: {Item.ruc}</span><span>{Item.direccion}</span><b>{Item.numero === 1 ? "Primera inspección" : "Segunda inspección"}</b></button>)}</div> : <Aviso>No tienes inspecciones por completar en esta fecha.</Aviso>}</Seccion>}{Detalle && <Seccion titulo={`Detalle de inspección ${Detalle.numero}`} acciones={<Boton secundario onClick={() => DefinirDetalle(null)}>Volver</Boton>}><div className="detalle"><div><span>RUC</span><b>{Detalle.ruc}</b></div><div><span>Razón social</span><b>{Detalle.razon_social}</b></div><div><span>Dirección</span><b>{Detalle.direccion}</b></div><div><span>Visita</span><b>{Detalle.numero === 1 ? "Primera" : "Segunda"}</b></div>{Detalle.numero === 2 && <div className="ancho"><span>Observaciones anteriores</span><b>{Detalle.observaciones_anteriores}</b></div>}</div><div className="acciones"><Boton secundario onClick={() => AbrirArchivoProtegido(`/inspector/inspecciones/${Detalle.id}/plano`)}>Descargar plano PDF</Boton><Boton onClick={Aprobar}>Aprobar licencia</Boton></div><Area etiqueta={Detalle.numero === 1 ? "Observaciones de la primera inspección" : "Motivo de rechazo en segunda inspección"} minLength="10" rows="4" value={Observaciones} onChange={(e) => DefinirObservaciones(e.target.value)} placeholder="Mínimo 10 caracteres" /><Boton peligro disabled={Observaciones.trim().length < 10} onClick={Observar}>{Detalle.numero === 1 ? "Registrar observaciones" : "Rechazar trámite"}</Boton></Seccion>}</div>;
}

