export const Roles = Object.freeze({
  CAJERO: "CAJERO",
  INSPECTOR: "INSPECTOR",
  ADMINISTRADOR: "ADMINISTRADOR",
  SUPERADMINISTRADOR: "SUPERADMINISTRADOR"
});

export const EstadosTramite = Object.freeze({
  PENDIENTE_PAGO: "PENDIENTE_PAGO",
  EN_PROCESO: "EN_PROCESO",
  EN_OBSERVACION: "EN_OBSERVACION",
  RECHAZADO: "RECHAZADO",
  APROBADO: "APROBADO",
  VENCIDO: "VENCIDO"
});

export const EstadosCaja = Object.freeze({
  SOLICITADA_APERTURA: "SOLICITADA_APERTURA",
  ABIERTA: "ABIERTA",
  SOLICITADA_CIERRE: "SOLICITADA_CIERRE",
  CERRADA: "CERRADA",
  RECHAZADA: "RECHAZADA"
});

export const TiposSolicitudCaja = Object.freeze({
  APERTURA: "APERTURA",
  INYECCION: "INYECCION",
  CIERRE: "CIERRE"
});
